services:
  server:
    build:
      context: ./server
    container_name: evently_server
    env_file:
      - ./server/.env
    environment:
      NODE_OPTIONS: --dns-result-order=ipv4first
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
    container_name: evently_client
    env_file:
      - ./client/.env
    ports:
      - "5173:5173"
    depends_on:
      - server
    restart: unless-stopped
    volumes:
      - ./client:/app
      - /app/node_modules
